Set-Service "AxInstSV" -StartupType Manual 
Set-Service "AJRouter" -StartupType Disabled 
Set-Service "AppReadiness" -StartupType Manual 
Set-Service "AppIDSvc" -StartupType Manual 
Set-Service "Appinfo" -StartupType Manual 
Set-Service "ALG" -StartupType Disabled 
Set-Service "AppMgmt" -StartupType Disabled 
Set-Service "AppXSVC" -StartupType Manual 
Set-Service "tzautoupdate" -StartupType Disabled 
Set-Service "BITS" -StartupType Automatic 
Set-Service "BrokerInfrastructure" -StartupType Automatic 
Set-Service "BFE" -StartupType Automatic 
Set-Service "BDESVC" -StartupType Manual 
Set-Service "wbengine" -StartupType Manual 
Set-Service "BthHFSrv" -StartupType Disabled 
Set-Service "bthserv" -StartupType Disabled 
Set-Service "PeerDistSvc" -StartupType Disabled 
Set-Service "camsvc" -StartupType Manual 
Set-Service "CertPropSvc" -StartupType Disabled 
Set-Service "NfsClnt" -StartupType Disabled 
Set-Service "ClipSVC" -StartupType Manual 
Set-Service "KeyIso" -StartupType Manual 
Set-Service "EventSystem" -StartupType Automatic 
Set-Service "COMSysApp" -StartupType Manual 
Set-Service "Browser" -StartupType Manual 
Set-Service "CDPSvc" -StartupType Automatic 
Set-Service "CDPUserSvc_?????" -StartupType Automatic 
Set-Service "DiagTrack" -StartupType Automatic 
Set-Service "PimIndexMaintenanceSvc_?????" -StartupType Manual 
Set-Service "CoreMessagingRegistrar" -StartupType Automatic 
Set-Service "VaultSvc" -StartupType Manual 
Set-Service "CryptSvc" -StartupType Automatic 
Set-Service "DsSvc" -StartupType Manual 
Set-Service "DusmSvc" -StartupType Automatic 
Set-Service "DcomLaunch" -StartupType Automatic 
Set-Service "DoSvc" -StartupType Automatic 
Set-Service "DeviceAssociationService" -StartupType Manual 
Set-Service "DeviceInstall" -StartupType Manual 
Set-Service "DmEnrollmentSvc" -StartupType Manual 
Set-Service "DsmSVC" -StartupType Manual 
Set-Service "DevicesFlowUserSvc_?????" -StartupType Manual 
Set-Service "DevQueryBroker" -StartupType Manual 
Set-Service "Dhcp" -StartupType Automatic 
Set-Service "diagsvc" -StartupType Manual 
Set-Service "DPS" -StartupType Automatic 
Set-Service "WdiServiceHost" -StartupType Manual 
Set-Service "WdiSystemHost" -StartupType Manual 
Set-Service "TrkWks" -StartupType Automatic 
Set-Service "MSDTC" -StartupType Manual 
Set-Service "dmwappushsvc" -StartupType Disabled 
Set-Service "Dnscache" -StartupType Automatic 
Set-Service "MapsBroker" -StartupType Disabled 
Set-Service "DsRoleSvc" -StartupType Not installed 
Set-Service "embeddedmode" -StartupType Manual 
Set-Service "EFS" -StartupType Manual 
Set-Service "EntAppSvc" -StartupType Manual 
Set-Service "EapHost" -StartupType Manual 
Set-Service "fhsvc" -StartupType Manual 
Set-Service "fdPHost" -StartupType Manual 
Set-Service "FDResPub" -StartupType Manual 
Set-Service "lfsvc" -StartupType Disabled 
Set-Service "GraphicsPerfSvc" -StartupType Manual 
Set-Service "gpsvc" -StartupType Automatic 
Set-Service "HomeGroupListener" -StartupType Manual 
Set-Service "HomeGroupProvider" -StartupType Manual 
Set-Service "hidserv" -StartupType Manual 
Set-Service "HvHost" -StartupType Disabled 
Set-Service "vmickvpexchange" -StartupType Disabled 
Set-Service "vmicguestinterface" -StartupType Disabled 
Set-Service "vmicshutdown" -StartupType Disabled 
Set-Service "vmicheartbeat" -StartupType Disabled 
Set-Service "vmicvmsession" -StartupType Disabled 
Set-Service "vmicrdv" -StartupType Disabled 
Set-Service "vmictimesync" -StartupType Disabled 
Set-Service "vmicvss" -StartupType Disabled 
Set-Service "IKEEXT" -StartupType Manual 
Set-Service "irmon" -StartupType Disabled 
Set-Service "UI0Detect" -StartupType Manual 
Set-Service "SharedAccess" -StartupType Disabled 
Set-Service "iphlpsvc" -StartupType Disabled 
Set-Service "IpxlatCfgSvc" -StartupType Disabled 
Set-Service "PolicyAgent" -StartupType Manual 
Set-Service "KtmRm" -StartupType Manual 
Set-Service "lltdsvc" -StartupType Manual 
Set-Service "wlpasvc" -StartupType Manual 
Set-Service "LSM" -StartupType Automatic 
Set-Service "MessagingService_?????" -StartupType Manual 
Set-Service "diagnosticshub.standardcollector.service" -StartupType Manual 
Set-Service "wlidsvc" -StartupType Manual 
Set-Service "AppVClient" -StartupType Disabled 
Set-Service "MSiSCSI" -StartupType Disabled 
Set-Service "NgcSvc" -StartupType Manual 
Set-Service "NgcCtnrSvc" -StartupType Manual 
Set-Service "swprv" -StartupType Manual 
Set-Service "smphost" -StartupType Manual 
Set-Service "SmsRouter" -StartupType Disabled 
Set-Service "NaturalAuthentication" -StartupType Disabled 
Set-Service "Netlogon" -StartupType Disabled 
Set-Service "NcdAutoSetup" -StartupType Disabled 
Set-Service "NcbService" -StartupType Manual 
Set-Service "Netman" -StartupType Manual 
Set-Service "NcaSVC" -StartupType Manual 
Set-Service "netprofm" -StartupType Manual 
Set-Service "NlaSvc" -StartupType Automatic 
Set-Service "NetSetupSvc" -StartupType Manual 
Set-Service "nsi" -StartupType Automatic 
Set-Service "CscService" -StartupType Disabled 
Set-Service "defragsvc" -StartupType Manual 
Set-Service "SEMgrSvc" -StartupType Disabled 
Set-Service "PNRPsvc" -StartupType Manual 
Set-Service "p2psvc" -StartupType Manual 
Set-Service "p2pimsvc" -StartupType Manual 
Set-Service "PerfHost" -StartupType Manual 
Set-Service "pla" -StartupType Manual 
Set-Service "PhoneSvc" -StartupType Disabled 
Set-Service "PlugPlay" -StartupType Manual 
Set-Service "PNRPAutoReg" -StartupType Manual 
Set-Service "WPDBusEnum" -StartupType Manual 
Set-Service "Power" -StartupType Automatic 
Set-Service "Spooler" -StartupType Automatic 
Set-Service "PrintNotify" -StartupType Manual 
Set-Service "PrintWorkflowUserSvc_?????" -StartupType Manual 
Set-Service "wercplsupport" -StartupType Manual 
Set-Service "PcaSvc" -StartupType Automatic 
Set-Service "QWAVE" -StartupType Manual 
Set-Service "RmSvc" -StartupType Manual 
Set-Service "RasAuto" -StartupType Manual 
Set-Service "RasMan" -StartupType Manual 
Set-Service "SessionEnv" -StartupType Disabled 
Set-Service "TermService" -StartupType Disabled 
Set-Service "UmRdpService" -StartupType Disabled 
Set-Service "RpcSs" -StartupType Automatic 
Set-Service "RpcLocator" -StartupType Disabled 
Set-Service "RemoteRegistry" -StartupType Disabled 
Set-Service "RetailDemo" -StartupType Disabled 
Set-Service "RemoteAccess" -StartupType Disabled 
Set-Service "RpcEptMapper" -StartupType Automatic 
Set-Service "seclogon" -StartupType Manual 
Set-Service "SstpSvc" -StartupType Manual 
Set-Service "SamSs" -StartupType Automatic 
Set-Service "wscsvc" -StartupType Automatic 
Set-Service "SensorDataService" -StartupType Disabled 
Set-Service "SensrSvc" -StartupType Disabled 
Set-Service "SensorService" -StartupType Disabled 
Set-Service "LanmanServer" -StartupType Automatic 
Set-Service "shpamsvc" -StartupType Disabled 
Set-Service "ShellHWDetection" -StartupType Automatic 
Set-Service "SCardSvr" -StartupType Disabled 
Set-Service "ScDeviceEnum" -StartupType Disabled 
Set-Service "SCPolicySvc" -StartupType Disabled 
Set-Service "SNMPTRAP" -StartupType Disabled 
Set-Service "sppsvc" -StartupType Automatic 
Set-Service "SharedRealitySvc" -StartupType Manual 
Set-Service "svsvc" -StartupType Manual 
Set-Service "SSDPSRV" -StartupType Manual 
Set-Service "StateRepository" -StartupType Manual 
Set-Service "WiaRpc" -StartupType Manual 
Set-Service "StorSvc" -StartupType Manual 
Set-Service "TieringEngineService" -StartupType Manual 
Set-Service "SysMain" -StartupType Automatic 
Set-Service "OneSyncSvc_?????" -StartupType Automatic 
Set-Service "SENS" -StartupType Automatic 
Set-Service "SystemEventsBroker" -StartupType Automatic 
Set-Service "Schedule" -StartupType Automatic 
Set-Service "lmhosts" -StartupType Manual 
Set-Service "TapiSrv" -StartupType Manual 
Set-Service "Themes" -StartupType Automatic 
Set-Service "tiledatamodelsvc" -StartupType Manual 
Set-Service "TimeBroker" -StartupType Manual 
Set-Service "TabletInputService" -StartupType Disabled 
Set-Service "UsoSvc" -StartupType Manual 
Set-Service "upnphost" -StartupType Manual 
Set-Service "UserDataSvc_?????" -StartupType Manual 
Set-Service "UnistoreSvc_?????" -StartupType Manual 
Set-Service "UevAgentService" -StartupType Disabled 
Set-Service "UserManager" -StartupType Automatic 
Set-Service "ProfSvc" -StartupType Automatic 
Set-Service "vds" -StartupType Manual 
Set-Service "VSS" -StartupType Manual 
Set-Service "WalletService" -StartupType Manual 
Set-Service "" -StartupType Manual 
Set-Service "TokenBroker" -StartupType Manual 
Set-Service "WebClient" -StartupType Disabled 
Set-Service "WFDSConSvc" -StartupType Disabled 
Set-Service "AudioSrv" -StartupType Automatic 
Set-Service "AudioEndpointBuilder" -StartupType Automatic 
Set-Service "SDRSVC" -StartupType Manual 
Set-Service "WbioSrvc" -StartupType Manual 
Set-Service "FrameServer" -StartupType Disabled 
Set-Service "wcncsvc" -StartupType Disabled 
Set-Service "Wcmsvc" -StartupType Automatic 
Set-Service "Sense" -StartupType Manual 
Set-Service "WdNisSvc" -StartupType Manual 
Set-Service "WinDefend" -StartupType Automatic 
Set-Service "MpsSvc" -StartupType Automatic 
Set-Service "SecurityHealthService" -StartupType Automatic 
Set-Service "WEPHOSTSVC" -StartupType Manual 
Set-Service "WerSvc" -StartupType Manual 
Set-Service "Wecsvc" -StartupType Manual 
Set-Service "EventLog" -StartupType Automatic 
Set-Service "FontCache" -StartupType Automatic 
Set-Service "StiSvc" -StartupType Manual 
Set-Service "wisvc" -StartupType Disabled 
Set-Service "msiserver" -StartupType Manual 
Set-Service "LicenseManager" -StartupType Manual 
Set-Service "Winmgmt" -StartupType Automatic 
Set-Service "WMPNetworkSvc" -StartupType Disabled 
Set-Service "icssvc" -StartupType Disabled 
Set-Service "TrustedInstaller" -StartupType Manual 
Set-Service "spectrum" -StartupType Manual 
Set-Service "WpnService" -StartupType Automatic 
Set-Service "WpnUserService_?????" -StartupType Manual 
Set-Service "WinRM" -StartupType Disabled 
Set-Service "WSearch" -StartupType Automatic 
Set-Service "InstallService" -StartupType Manual 
Set-Service "W32Time" -StartupType Manual 
Set-Service "wuauserv" -StartupType Manual 
Set-Service "WinHttpAutoProxySvc" -StartupType Manual 
Set-Service "dot3svc" -StartupType Manual 
Set-Service "WlanSvc" -StartupType Manual 
Set-Service "wmiApSrv" -StartupType Manual 
Set-Service "LanmanWorkstation" -StartupType Automatic 
Set-Service "WwanSvc" -StartupType Disabled 
Set-Service "XboxGipSvc" -StartupType Manual 
Set-Service "xbgm" -StartupType Disabled 
Set-Service "XblAuthManager" -StartupType Disabled 
Set-Service "XblGameSave" -StartupType Disabled 
Set-Service "XboxNetApiSvc" -StartupType Disabled 
