Set-Service "AxInstSV" -StartupType Manual 
Set-Service "SensrSvc" -StartupType Manual 
Set-Service "AeLookupSvc" -StartupType Manual 
Set-Service "AppIDSvc" -StartupType Manual 
Set-Service "Appinfo" -StartupType Manual 
Set-Service "ALG" -StartupType Manual 
Set-Service "AppMgmt" -StartupType Manual 
Set-Service "BITS" -StartupType Manual 
Set-Service "BFE" -StartupType Automatic 
Set-Service "BDESVC" -StartupType Manual 
Set-Service "wbengine" -StartupType Manual 
Set-Service "bthserv" -StartupType Manual 
Set-Service "PeerDistSvc" -StartupType Manual 
Set-Service "CertPropSvc" -StartupType Manual 
Set-Service "KeyIso" -StartupType Manual 
Set-Service "EventSystem" -StartupType Automatic 
Set-Service "COMSysApp" -StartupType Manual 
Set-Service "Browser" -StartupType Manual 
Set-Service "VaultSvc" -StartupType Manual 
Set-Service "CryptSvc" -StartupType Automatic 
Set-Service "DcomLaunch" -StartupType Automatic 
Set-Service "UxSms" -StartupType Automatic 
Set-Service "Dhcp" -StartupType Automatic 
Set-Service "DPS" -StartupType Automatic 
Set-Service "WdiServiceHost" -StartupType Manual 
Set-Service "WdiSystemHost" -StartupType Manual 
Set-Service "defragsvc" -StartupType Manual 
Set-Service "TrkWks" -StartupType Automatic 
Set-Service "MSDTC" -StartupType Manual 
Set-Service "Dnscache" -StartupType Automatic 
Set-Service "EFS" -StartupType Manual 
Set-Service "EapHost" -StartupType Manual 
Set-Service "Fax" -StartupType Manual 
Set-Service "fdPHost" -StartupType Manual 
Set-Service "FDResPub" -StartupType Automatic 
Set-Service "gpsvc" -StartupType Automatic 
Set-Service "hkmsvc" -StartupType Manual 
Set-Service "HomeGroupListener" -StartupType Manual 
Set-Service "HomeGroupProvider" -StartupType Manual 
Set-Service "hidserv" -StartupType Manual 
Set-Service "IKEEXT" -StartupType Manual 
Set-Service "UI0Detect" -StartupType Manual 
Set-Service "SharedAccess" -StartupType Disabled 
Set-Service "iphlpsvc" -StartupType Automatic 
Set-Service "PolicyAgent" -StartupType Manual 
Set-Service "KtmRm" -StartupType Manual 
Set-Service "lltdsvc" -StartupType Manual 
Set-Service "Mcx2Svc" -StartupType Disabled 
Set-Service "clr_optimization_v2.0.50727" -StartupType Manual 
Set-Service "MSiSCSI" -StartupType Manual 
Set-Service "swprv" -StartupType Manual 
Set-Service "MMCSS" -StartupType Automatic 
Set-Service "NetTcpPortSharing" -StartupType Disabled 
Set-Service "Netlogon" -StartupType Manual 
Set-Service "napagent" -StartupType Manual 
Set-Service "Netman" -StartupType Manual 
Set-Service "netprofm" -StartupType Manual 
Set-Service "NlaSvc" -StartupType Automatic 
Set-Service "nsi" -StartupType Automatic 
Set-Service "CscService" -StartupType Automatic 
Set-Service "WPCSvc" -StartupType Manual 
Set-Service "PNRPsvc" -StartupType Manual 
Set-Service "p2psvc" -StartupType Manual 
Set-Service "p2pimsvc" -StartupType Manual 
Set-Service "pla" -StartupType Manual 
Set-Service "PlugPlay" -StartupType Automatic 
Set-Service "IPBusEnum" -StartupType Manual 
Set-Service "PNRPAutoReg" -StartupType Manual 
Set-Service "WPDBusEnum" -StartupType Manual 
Set-Service "Power" -StartupType Automatic 
Set-Service "Spooler" -StartupType Automatic 
Set-Service "wercplsupport" -StartupType Manual 
Set-Service "PcaSvc" -StartupType Manual 
Set-Service "ProtectedStorage" -StartupType Manual 
Set-Service "QWAVE" -StartupType Manual 
Set-Service "RasAuto" -StartupType Manual 
Set-Service "RasMan" -StartupType Manual 
Set-Service "SessionEnv" -StartupType Manual 
Set-Service "TermService" -StartupType Manual 
Set-Service "UmRdpService" -StartupType Manual 
Set-Service "RpcSs" -StartupType Automatic 
Set-Service "RpcLocator" -StartupType Manual 
Set-Service "RemoteRegistry" -StartupType Manual 
Set-Service "RemoteAccess" -StartupType Disabled 
Set-Service "RpcEptMapper" -StartupType Automatic 
Set-Service "seclogon" -StartupType Manual 
Set-Service "SstpSvc" -StartupType Manual 
Set-Service "SamSs" -StartupType Automatic 
Set-Service "wscsvc" -StartupType Automatic 
Set-Service "LanmanServer" -StartupType Automatic 
Set-Service "ShellHWDetection" -StartupType Automatic 
Set-Service "SCardSvr" -StartupType Manual 
Set-Service "SCPolicySvc" -StartupType Manual 
Set-Service "SNMPTRAP" -StartupType Manual 
Set-Service "sppsvc" -StartupType Automatic 
Set-Service "sppuinotify" -StartupType Manual 
Set-Service "SSDPSRV" -StartupType Manual 
Set-Service "StorSvc" -StartupType Not Available 
Set-Service "SysMain" -StartupType Automatic 
Set-Service "SENS" -StartupType Automatic 
Set-Service "TabletInputService" -StartupType Manual 
Set-Service "Schedule" -StartupType Automatic 
Set-Service "lmhosts" -StartupType Automatic 
Set-Service "TapiSrv" -StartupType Manual 
Set-Service "Themes" -StartupType Automatic 
Set-Service "THREADORDER" -StartupType Manual 
Set-Service "TBS" -StartupType Manual 
Set-Service "upnphost" -StartupType Manual 
Set-Service "ProfSvc" -StartupType Automatic 
Set-Service "vds" -StartupType Manual 
Set-Service "VSS" -StartupType Manual 
Set-Service "WebClient" -StartupType Manual 
Set-Service "AudioSrv" -StartupType Automatic 
Set-Service "AudioEndpointBuilder" -StartupType Automatic 
Set-Service "SDRSVC" -StartupType Manual 
Set-Service "WbioSrvc" -StartupType Manual 
Set-Service "idsvc" -StartupType Manual 
Set-Service "WcsPlugInService" -StartupType Manual 
Set-Service "wcncsvc" -StartupType Manual 
Set-Service "WinDefend" -StartupType Automatic 
Set-Service "wudfsvc" -StartupType Manual 
Set-Service "WerSvc" -StartupType Manual 
Set-Service "Wecsvc" -StartupType Manual 
Set-Service "EventLog" -StartupType Automatic 
Set-Service "MpsSvc" -StartupType Automatic 
Set-Service "FontCache" -StartupType Automatic 
Set-Service "StiSvc" -StartupType Manual 
Set-Service "msiserver" -StartupType Manual 
Set-Service "Winmgmt" -StartupType Automatic 
Set-Service "ehRecvr" -StartupType Manual 
Set-Service "ehSched" -StartupType Manual 
Set-Service "WMPNetworkSvc" -StartupType Manual 
Set-Service "TrustedInstaller" -StartupType Manual 
Set-Service "FontCache3.0.0.0" -StartupType Manual 
Set-Service "WinRM" -StartupType Manual 
Set-Service "WSearch" -StartupType Automatic 
Set-Service "W32Time" -StartupType Manual 
Set-Service "wuauserv" -StartupType Automatic 
Set-Service "WinHttpAutoProxySvc" -StartupType Manual 
Set-Service "dot3svc" -StartupType Manual 
Set-Service "Wlansvc" -StartupType Manual 
Set-Service "wmiApSrv" -StartupType Manual 
Set-Service "LanmanWorkstation" -StartupType Automatic 
Set-Service "WwanSvc" -StartupType Manual 
