Set-Service "AxInstSV" -StartupType Manual 
Set-Service "AppReadiness" -StartupType Manual 
Set-Service "AeLookupSvc" -StartupType Manual 
Set-Service "AppIDSvc" -StartupType Manual 
Set-Service "Appinfo" -StartupType Manual 
Set-Service "ALG" -StartupType Manual 
Set-Service "AppXSVC" -StartupType Manual 
Set-Service "AppMgmt" -StartupType Not Available 
Set-Service "BITS" -StartupType Automatic 
Set-Service "BrokerInfrastructure" -StartupType Automatic 
Set-Service "BFE" -StartupType Automatic 
Set-Service "BDESVC" -StartupType Manual 
Set-Service "wbengine" -StartupType Manual 
Set-Service "bthserv" -StartupType Manual 
Set-Service "PeerDistSvc" -StartupType Not Available 
Set-Service "CertPropSvc" -StartupType Manual 
Set-Service "NfsClnt" -StartupType Not Available 
Set-Service "KeyIso" -StartupType Manual 
Set-Service "EventSystem" -StartupType Automatic 
Set-Service "COMSysApp" -StartupType Manual 
Set-Service "Browser" -StartupType Manual 
Set-Service "VaultSvc" -StartupType Manual 
Set-Service "CryptSvc" -StartupType Automatic 
Set-Service "DcomLaunch" -StartupType Automatic 
Set-Service "DeviceAssociationService" -StartupType Automatic 
Set-Service "DeviceInstall" -StartupType Manual 
Set-Service "DsmSVC" -StartupType Manual 
Set-Service "Dhcp" -StartupType Automatic 
Set-Service "DPS" -StartupType Automatic 
Set-Service "WdiServiceHost" -StartupType Manual 
Set-Service "WdiSystemHost" -StartupType Manual 
Set-Service "TrkWks" -StartupType Automatic 
Set-Service "MSDTC" -StartupType Manual 
Set-Service "Dnscache" -StartupType Automatic 
Set-Service "DsRoleSvc" -StartupType Not Available 
Set-Service "EFS" -StartupType Manual 
Set-Service "EapHost" -StartupType Manual 
Set-Service "WPCSvc" -StartupType Manual 
Set-Service "Fax" -StartupType Manual 
Set-Service "fhsvc" -StartupType Manual 
Set-Service "fdPHost" -StartupType Manual 
Set-Service "FDResPub" -StartupType Manual 
Set-Service "gpsvc" -StartupType Automatic 
Set-Service "hkmsvc" -StartupType Manual 
Set-Service "HomeGroupListener" -StartupType Manual 
Set-Service "HomeGroupProvider" -StartupType Manual 
Set-Service "hidserv" -StartupType Manual 
Set-Service "vmickvpexchange" -StartupType Manual 
Set-Service "vmicguestinterface" -StartupType Manual 
Set-Service "vmicshutdown" -StartupType Manual 
Set-Service "vmicheartbeat" -StartupType Manual 
Set-Service "vmicrdv" -StartupType Manual 
Set-Service "vmictimesync" -StartupType Manual 
Set-Service "vmicvss" -StartupType Manual 
Set-Service "IKEEXT" -StartupType Manual 
Set-Service "UI0Detect" -StartupType Manual 
Set-Service "SharedAccess" -StartupType Disabled 
Set-Service "IEEtwCollectorService" -StartupType Manual 
Set-Service "iphlpsvc" -StartupType Automatic 
Set-Service "PolicyAgent" -StartupType Manual 
Set-Service "KtmRm" -StartupType Manual 
Set-Service "lltdsvc" -StartupType Manual 
Set-Service "LSM" -StartupType Automatic 
Set-Service "wlidsvc" -StartupType Manual 
Set-Service "MSiSCSI" -StartupType Manual 
Set-Service "swprv" -StartupType Manual 
Set-Service "MMCSS" -StartupType Automatic 
Set-Service "NetTcpPortSharing" -StartupType Disabled 
Set-Service "Netlogon" -StartupType Manual 
Set-Service "napagent" -StartupType Manual 
Set-Service "NcdAutoSetup" -StartupType Manual 
Set-Service "NcbService" -StartupType Manual 
Set-Service "Netman" -StartupType Manual 
Set-Service "NcaSVC" -StartupType Manual 
Set-Service "netprofm" -StartupType Manual 
Set-Service "NlaSvc" -StartupType Automatic 
Set-Service "nsi" -StartupType Automatic 
Set-Service "CscService" -StartupType Not Available 
Set-Service "defragsvc" -StartupType Manual 
Set-Service "PNRPsvc" -StartupType Manual 
Set-Service "p2psvc" -StartupType Manual 
Set-Service "p2pimsvc" -StartupType Manual 
Set-Service "pla" -StartupType Manual 
Set-Service "PlugPlay" -StartupType Manual 
Set-Service "PNRPAutoReg" -StartupType Manual 
Set-Service "WPDBusEnum" -StartupType Manual 
Set-Service "Power" -StartupType Automatic 
Set-Service "Spooler" -StartupType Automatic 
Set-Service "PrintNotify" -StartupType Manual 
Set-Service "wercplsupport" -StartupType Manual 
Set-Service "PcaSvc" -StartupType Automatic 
Set-Service "QWAVE" -StartupType Manual 
Set-Service "RasAuto" -StartupType Manual 
Set-Service "RasMan" -StartupType Manual 
Set-Service "SessionEnv" -StartupType Manual 
Set-Service "UmRdpService" -StartupType Manual 
Set-Service "TermService" -StartupType Manual 
Set-Service "RpcSs" -StartupType Automatic 
Set-Service "RpcLocator" -StartupType Manual 
Set-Service "RemoteRegistry" -StartupType Disabled 
Set-Service "RemoteAccess" -StartupType Disabled 
Set-Service "RpcEptMapper" -StartupType Automatic 
Set-Service "seclogon" -StartupType Manual 
Set-Service "SstpSvc" -StartupType Manual 
Set-Service "SamSs" -StartupType Automatic 
Set-Service "wscsvc" -StartupType Automatic 
Set-Service "SensrSvc" -StartupType Manual 
Set-Service "LanmanServer" -StartupType Automatic 
Set-Service "ShellHWDetection" -StartupType Automatic 
Set-Service "SCardSvr" -StartupType Disabled 
Set-Service "ScDeviceEnum" -StartupType Manual 
Set-Service "SCPolicySvc" -StartupType Manual 
Set-Service "SNMPTRAP" -StartupType Manual 
Set-Service "sppsvc" -StartupType Automatic 
Set-Service "svsvc" -StartupType Manual 
Set-Service "SSDPSRV" -StartupType Manual 
Set-Service "WiaRpc" -StartupType Manual 
Set-Service "StorSvc" -StartupType Manual 
Set-Service "SysMain" -StartupType Automatic 
Set-Service "SENS" -StartupType Automatic 
Set-Service "SystemEventsBroker" -StartupType Automatic 
Set-Service "Schedule" -StartupType Automatic 
Set-Service "lmhosts" -StartupType Automatic 
Set-Service "TapiSrv" -StartupType Manual 
Set-Service "Themes" -StartupType Automatic 
Set-Service "THREADORDER" -StartupType Manual 
Set-Service "TimeBroker" -StartupType Manual 
Set-Service "TabletInputService" -StartupType Manual 
Set-Service "upnphost" -StartupType Manual 
Set-Service "ProfSvc" -StartupType Automatic 
Set-Service "vds" -StartupType Manual 
Set-Service "VSS" -StartupType Manual 
Set-Service "WebClient" -StartupType Manual 
Set-Service "AudioSrv" -StartupType Automatic 
Set-Service "AudioEndpointBuilder" -StartupType Automatic 
Set-Service "WbioSrvc" -StartupType Manual 
Set-Service "WcsPlugInService" -StartupType Manual 
Set-Service "wcncsvc" -StartupType Manual 
Set-Service "Wcmsvc" -StartupType Automatic 
Set-Service "WdNisSvc" -StartupType Manual 
Set-Service "WinDefend" -StartupType Automatic 
Set-Service "wudfsvc" -StartupType Manual 
Set-Service "WEPHOSTSVC" -StartupType Manual 
Set-Service "WerSvc" -StartupType Manual 
Set-Service "Wecsvc" -StartupType Manual 
Set-Service "EventLog" -StartupType Automatic 
Set-Service "MpsSvc" -StartupType Automatic 
Set-Service "FontCache" -StartupType Automatic 
Set-Service "StiSvc" -StartupType Manual 
Set-Service "msiserver" -StartupType Manual 
Set-Service "lfsvc" -StartupType Manual 
Set-Service "Winmgmt" -StartupType Automatic 
Set-Service "WMPNetworkSvc" -StartupType Manual 
Set-Service "TrustedInstaller" -StartupType Manual 
Set-Service "WinRM" -StartupType Manual 
Set-Service "WSearch" -StartupType Automatic 
Set-Service "WSService" -StartupType Manual 
Set-Service "W32Time" -StartupType Manual 
Set-Service "wuauserv" -StartupType Manual 
Set-Service "WinHttpAutoProxySvc" -StartupType Manual 
Set-Service "dot3svc" -StartupType Manual 
Set-Service "WlanSvc" -StartupType Manual 
Set-Service "wmiApSrv" -StartupType Manual 
Set-Service "workfolderssvc" -StartupType Manual 
Set-Service "LanmanWorkstation" -StartupType Automatic 
Set-Service "WwanSvc" -StartupType Manual 
