Set-Service "Alerter" -StartupType Disabled 
Set-Service "ALG" -StartupType Manual 
Set-Service "AppMgmt" -StartupType Manual 
Set-Service "wuauserv" -StartupType Automatic 
Set-Service "BITS" -StartupType Manual 
Set-Service "ClipSrv" -StartupType Disabled 
Set-Service "EventSystem" -StartupType Manual 
Set-Service "COMSysApp" -StartupType Manual 
Set-Service "Browser" -StartupType Automatic 
Set-Service "CryptSvc" -StartupType Automatic 
Set-Service "DcomLaunch" -StartupType Automatic 
Set-Service "Dhcp" -StartupType Automatic 
Set-Service "TrkWks" -StartupType Manual 
Set-Service "MSDTC" -StartupType Manual 
Set-Service "Dnscache" -StartupType Automatic 
Set-Service "ERSvc" -StartupType Disabled 
Set-Service "Eventlog" -StartupType Automatic 
Set-Service "EapHost" -StartupType Disabled 
Set-Service "FastUserSwitchingCompatibility" -StartupType Disabled 
Set-Service "hkmsvc" -StartupType Disabled 
Set-Service "helpsvc" -StartupType Disabled 
Set-Service "HTTPFilter" -StartupType Disabled 
Set-Service "HidServ" -StartupType Disabled 
Set-Service "ImapiService" -StartupType Manual 
Set-Service "cisvc" -StartupType Disabled 
Set-Service "PolicyAgent" -StartupType Disabled 
Set-Service "dmserver" -StartupType Manual 
Set-Service "dmadmin" -StartupType Manual 
Set-Service "ehRecvr" -StartupType Disabled 
Set-Service "ehSched" -StartupType Disabled 
Set-Service "Messenger" -StartupType Disabled 
Set-Service "MHN" -StartupType Disabled 
Set-Service "SwPrv" -StartupType Disabled 
Set-Service "Netlogon" -StartupType Disabled 
Set-Service "mnmsrvc" -StartupType Disabled 
Set-Service "napagent" -StartupType Manual 
Set-Service "Netman" -StartupType Manual 
Set-Service "NetDDE" -StartupType Disabled 
Set-Service "NetDDEdsdm" -StartupType Disabled 
Set-Service "Nla" -StartupType Manual 
Set-Service "xmlprov" -StartupType Disabled 
Set-Service "NtLmSsp" -StartupType Manual 
Set-Service "SysmonLog" -StartupType Disabled 
Set-Service "PlugPlay" -StartupType Automatic 
Set-Service "WmdmPmSN" -StartupType Disabled 
Set-Service "Spooler" -StartupType Automatic 
Set-Service "ProtectedStorage" -StartupType Disabled 
Set-Service "RSVP" -StartupType Disabled 
Set-Service "RasAuto" -StartupType Disabled 
Set-Service "RasMan" -StartupType Disabled 
Set-Service "RDSessMgr" -StartupType Disabled 
Set-Service "RpcSs" -StartupType Automatic 
Set-Service "RpcLocator" -StartupType Manual 
Set-Service "RemoteRegistry" -StartupType Disabled 
Set-Service "NtmsSvc" -StartupType Disabled 
Set-Service "RemoteAccess" -StartupType Disabled 
Set-Service "seclogon" -StartupType Disabled 
Set-Service "SamSs" -StartupType Automatic 
Set-Service "wscsvc" -StartupType Disabled 
Set-Service "lanmanserver" -StartupType Automatic 
Set-Service "ShellHWDetection" -StartupType Automatic 
Set-Service "SCardSvr" -StartupType Disabled 
Set-Service "SSDPSRV" -StartupType Disabled 
Set-Service "SENS" -StartupType Disabled 
Set-Service "srservice" -StartupType Disabled 
Set-Service "Schedule" -StartupType Automatic 
Set-Service "LmHosts" -StartupType Disabled 
Set-Service "TapiSrv" -StartupType Manual 
Set-Service "TlntSvr" -StartupType Disabled 
Set-Service "TermService" -StartupType Disabled 
Set-Service "Themes" -StartupType Disabled 
Set-Service "UPS" -StartupType Disabled 
Set-Service "upnphost" -StartupType Disabled 
Set-Service "VSS" -StartupType Disabled 
Set-Service "WebClient" -StartupType Disabled 
Set-Service "AudioSrv" -StartupType Automatic 
Set-Service "SharedAccess" -StartupType Automatic 
Set-Service "stisvc" -StartupType Disabled 
Set-Service "MSIServer" -StartupType Manual 
Set-Service "winmgmt" -StartupType Automatic 
Set-Service "Wmi" -StartupType Manual 
Set-Service "W32Time" -StartupType Disabled 
Set-Service "Dot3svc" -StartupType Disabled 
Set-Service "WZCSVC" -StartupType Disabled 
Set-Service "WmiApSrv" -StartupType Disabled 
Set-Service "lanmanworkstation" -StartupType Automatic 
