Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "alg.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "clipsrv.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "dllhost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "msdtc.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "services.exe" -StartupType Automatic 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "imapi.exe" -StartupType Disabled 
Set-Service "cisvc.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "lsass.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "dmadmin.exe" -StartupType Disabled 
Set-Service "services.exe" -StartupType Disabled 
Set-Service "dllhost.exe" -StartupType Disabled 
Set-Service "lsass.exe" -StartupType Disabled 
Set-Service "mnmsrvc.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Manual 
Set-Service "netdde.exe" -StartupType Disabled 
Set-Service "netdde.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "lsass.exe" -StartupType Disabled 
Set-Service "smlogsvc.exe" -StartupType Disabled 
Set-Service "services.exe" -StartupType Automatic 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "spoolsv.exe" -StartupType Disabled 
Set-Service "lsass.exe" -StartupType Disabled 
Set-Service "rsvp.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "sessmgr.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Automatic 
Set-Service "locator.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "lsass.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "SCardSvr.exe" -StartupType Disabled 
Set-Service "SCardSvr.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "tlntsvr.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "ups.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "vssvc.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Automatic 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "msiexec.exe" -StartupType Manual 
Set-Service "svchost.exe" -StartupType Automatic 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Disabled 
Set-Service "wmiapsrv.exe" -StartupType Disabled 
Set-Service "svchost.exe" -StartupType Automatic 
